### ISSUE TITLE
no pagination generated in github

### ISSUE THREAD

**Issue by sarbbottam** [octopress/paginate#36]
I am not sure what is going on, please refer https://github.com/sarbbottam/sarbbottam.github.io/commit/64d44fac03457d501598b597f1f6ec21b0c78b04

Everything worked fine at localhost:4000.

However, it resulted in a page w/o any pagination at github.

![screen shot 2016-10-23 at 12 46 44 pm](https://cloud.githubusercontent.com/assets/949380/19628943/cdf578ec-991e-11e6-9821-2083964aaaa2.png)

I have revert back to the previous commit to make https://sarbbottam.github.io/ work as desired.

Any pointer would be helpful.

Thanks!

**Comment by egeis** [comment]
Normally when pagination doesn't generate when I was starting out learning jekyll is because of some error, either a misplaced tab in the YML or liquid related error.  Did you build locally using an error reporting flags?

**Comment by sarbbottam** [comment]
> error reporting flags?

`-- trace`?

**Comment by egeis** [comment]
i think so, the info can be found on the jekyll homepage.  Also I took a look at my one working jekyll project and saw I added:

`# Collection Settings
collections:
   posts:
     permalink: /blog/:categories/:title.html
     output: true`

to my _config.yml.

I have a working octopress setup at [jekyll-modern-business](https://github.com/egeis/jekyll-modern-business). I want to point out im using forked version of this plugin to suppress some deprecated notifications.

**Comment by sarbbottam** [comment]
Thanks for the info, but I am not sure if I am following you. 

Everything works fine in local setup, it breaks only at github,`paginator` seems to be empty at github.

> `collections: posts: permalink: /blog/:categories/:title.html output: true`

Also why do I need an explicit `collections` setting for `posts`?

**Comment by sarbbottam** [comment]
Closing the issue as it is not because of `octopress-paginate`. GitHub pages does not support `octopress-paginate` https://github.com/github/pages-gem/issues/257.

**Comment by egeis** [comment]
No it doea not. Why you add travis ci to issue jekyll build when you commit.

**Comment by sarbbottam** [comment]
@egeis I don't know why I didn't set up a `Travis` build. Thanks for the reminder. I have updated the workflow. Planning to write a post on my experience with Jekyll and GitHub Pages. It might be helpful for folks like me who are starting with Jekyll and GitHub Pages.

**Comment by egeis** [comment]
@sarbbottam glad I can help.  `Travis`opens a lot of doors to plugins `gh-pages` would does not support.
