### ISSUE TITLE
Paginate through all documents

### ISSUE THREAD

**Issue by ChrisChinchilla** [octopress/paginate#38]
Hi @parkr and thanks for the great plugin.

Is there a way to paginate through all collections, posts etc? For a sort of home page that aggregates all updates across a site.

**Comment by parkr** [comment]
Hey @ChrisChinchilla, you would have to iterate over the collections themselves:

```liquid
{% for document in site.collections %}
  <a href="{{ document.url }}">{{ document.title }}</a>
{% endfor %}
```

This is not possible for pagination, however.
